### ISSUE TITLE
Github Example fails:

### ISSUE THREAD

**Issue by JRAndreassen** [rust-playground/proteus#2]
Hi...
 Great idea... and Lib...
I was thinking about the same, since I have a large number of generated libraries i have to normalize...

The example "examples/github.rs" fails... 
"add(value.ddfk, trim(value.ferwf))", "deans_name"),
Error: InvalidActionName { name: "add" }

Oversight perhaps ? there is no Action named "add"...

Any other actions planned ... :)

**Comment by deankarn** [comment]
@JRAndreassen Thanks for reporting, yes accidentally checking in something there, fixing. Sorry for the late reply, this message somehow slipped through the cracks.

Currently I don't have a lot of time, but implementing other actions should be pretty straight forward, happy to accept PR's :)

An example of adding one can be found [here](https://github.com/rust-playground/proteus/pull/1).
The level of complexity will all depend on the action itself.

**Comment by deankarn** [comment]
fixed by #3

**Comment by JRAndreassen** [comment]
@deankarn : No Worries, I know how it goes...
We all have time constrainte...
I'll see what I can do..
